-- =============================================
-- 1. TABLAS DE CATALOGO (Independientes)
-- =============================================

-- 1.1. Roles
CREATE TABLE "Rol" (
  "id" INTEGER PRIMARY KEY,
  "nombre_rol" VARCHAR UNIQUE NOT NULL,
  "descripcion" VARCHAR
);

-- 1.2. Especialidades (Movida aquí arriba para que Medico la encuentre)
CREATE TABLE "Especialidad" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR UNIQUE NOT NULL,
  "descripcion" VARCHAR
);

-- 1.3. Obras Sociales
CREATE TABLE "ObraSocial" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR UNIQUE NOT NULL
);

-- 1.4. Prestaciones
CREATE TABLE "Prestacion" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR NOT NULL,
  "precio_base" NUMERIC(10, 2) NOT NULL
);

-- =============================================
-- 2. TABLAS DE USUARIOS Y PERFILES
-- =============================================

-- 2.1. Users (Vinculada a Auth)
CREATE TABLE "Users" (
  "id" UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  "email" VARCHAR UNIQUE NOT NULL,
  "username" VARCHAR UNIQUE,
  "id_role" INTEGER REFERENCES "Rol" ("id") ON DELETE SET NULL
);

-- 2.2. Planes (Depende de OS)
CREATE TABLE "Plan" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" VARCHAR NOT NULL,
  "id_obra_social" INTEGER REFERENCES "ObraSocial" ("id") ON DELETE CASCADE
);

-- 2.3. Cliente
CREATE TABLE "Cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" UUID UNIQUE REFERENCES "Users" ("id") ON DELETE CASCADE,
  "nombre" VARCHAR NOT NULL,
  "apellido" VARCHAR NOT NULL,
  "dni" VARCHAR UNIQUE NOT NULL,
  "fecha_nacimiento" TIMESTAMP,
  "telefono" VARCHAR,
  "id_plan" INTEGER REFERENCES "Plan" ("id") ON DELETE SET NULL,
  "numero_afiliado" VARCHAR
);

-- 2.4. Medico (Ahora sí funciona porque Especialidad ya existe)
CREATE TABLE "Medico" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" UUID UNIQUE REFERENCES "Users" ("id") ON DELETE CASCADE,
  "matricula" VARCHAR UNIQUE NOT NULL,
  "id_especialidad" INTEGER NOT NULL REFERENCES "Especialidad" ("id") ON DELETE SET NULL,
  "precio_consulta" NUMERIC(10, 2) NOT NULL
);

-- =============================================
-- 3. REGLAS DE NEGOCIO Y OPERATORIA
-- =============================================

-- 3.1. Cobertura
CREATE TABLE "Cobertura" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_plan" INTEGER REFERENCES "Plan" ("id") ON DELETE CASCADE,
  "id_prestacion" INTEGER REFERENCES "Prestacion" ("id") ON DELETE CASCADE,
  "porcentaje_cobertura" INTEGER NOT NULL,
  "monto_coseguro" NUMERIC(10, 2) NOT NULL DEFAULT 0
);

-- 3.2. Turno
CREATE TABLE "Turno" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fecha_hora_inicio" TIMESTAMP NOT NULL,
  "fecha_hora_fin" TIMESTAMP NOT NULL,
  "estado" VARCHAR NOT NULL DEFAULT 'Disponible',
  "id_medico" INTEGER NOT NULL REFERENCES "Medico" ("id") ON DELETE CASCADE,
  "id_cliente" INTEGER REFERENCES "Cliente" ("id") ON DELETE CASCADE,
  "id_prestacion" INTEGER REFERENCES "Prestacion" ("id") ON DELETE SET NULL
);
-- Índice para velocidad
CREATE INDEX idx_turno_fecha ON "Turno" ("fecha_hora_inicio");

-- =============================================
-- 4. TABLAS DE SEGUIMIENTO (Historial, Recetas, Logs)
-- =============================================

-- 4.1. Notificaciones
CREATE TABLE "Notificaciones" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_turno" INTEGER NOT NULL REFERENCES "Turno" ("id") ON DELETE CASCADE,
  "fecha_envio" TIMESTAMP DEFAULT NOW(),
  "tipo" VARCHAR NOT NULL, 
  "destino" VARCHAR NOT NULL, 
  "estado" VARCHAR NOT NULL DEFAULT 'Enviado',
  "mensaje_error" VARCHAR
);

-- 4.2. Receta
CREATE TABLE "Receta" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_turno" INTEGER REFERENCES "Turno" ("id"),
  "id_medico" INTEGER NOT NULL REFERENCES "Medico" ("id"),
  "id_cliente" INTEGER NOT NULL REFERENCES "Cliente" ("id"),
  "fecha_emision" TIMESTAMP DEFAULT NOW(),
  "archivo_url" VARCHAR, 
  "detalle_medicamentos" JSONB
);

-- 4.3. Historia Clinica
CREATE TABLE "HistoriaClinica" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "created_at" TIMESTAMP DEFAULT NOW(),
  "id_cliente" INTEGER NOT NULL REFERENCES "Cliente" ("id") ON DELETE CASCADE,
  "id_medico" INTEGER NOT NULL REFERENCES "Medico" ("id"),
  "id_turno" INTEGER REFERENCES "Turno" ("id"),
  "motivo_consulta" TEXT NOT NULL,
  "signos_vitales" JSONB, 
  "observaciones" TEXT,
  "diagnostico" TEXT,
  "tratamiento" TEXT,
  "archivos_adjuntos" TEXT[] 
);

-- =============================================
-- 5. TRIGGER MAGIC (OBLIGATORIO)
-- =============================================

-- Función que copia el usuario
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public
AS $$
BEGIN
  INSERT INTO public."Users" (id, email, username, id_role)
  VALUES (
    new.id, 
    new.email, 
    new.raw_user_meta_data ->> 'username', 
    1 -- ASIGNA ROL 1 (PACIENTE) POR DEFECTO
  );
  RETURN new;
END;
$$;

-- Disparador
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- =============================================
-- 6. DATOS NECESARIOS (SEED)
-- =============================================
-- Insertamos roles para que el Trigger no falle al intentar asignar el rol 1
INSERT INTO "Rol" ("id", "nombre_rol", "descripcion") VALUES 
(1, 'Paciente', 'Usuario regular'),
(2, 'Medico', 'Profesional de salud'),
(3, 'Admin', 'Administrador del sistema'),
(4, 'Recepcionista', 'Gestiona turnos')
ON CONFLICT DO NOTHING;